pubmed_config:
  embeddings_directory: "/mnt/h/pubmed_semantic_search/pubmed_semantic_search//test/pubmed25_update_embed/"
  xml_directory: "/mnt/h/pubmed_semantic_search/pubmed_semantic_search//pubmed25_update_xmls/"
  npy_files_pattern: "*.npy"
  chunk_dir: "/home/dzyla/chunked/chunked_pubmed_embeddings/"
  metadata_path: "/mnt/h/pubmed_semantic_search/pubmed_semantic_search//pubmed_chunked_metadata.json"
  data_folder: "/mnt/h/pubmed_semantic_search/pubmed_semantic_search//test/pubmed25_update_df/"
  chunk_size_bytes: 1073741824  # 1GB in bytes

biorxiv_config:
  embeddings_directory: "/mnt/h/pubmed_semantic_search/pubmed_semantic_search//biorxiv_embed/"
  npy_files_pattern: "*.npy"
  combined_data_file: "/mnt/h/pubmed_semantic_search/pubmed_semantic_search//biorxiv_df/combined_biorxiv_data.parquet"
  chunk_dir: "/home/dzyla/chunked/chunked_biorxiv_embeddings/"
  metadata_path: "/mnt/h/pubmed_semantic_search/pubmed_semantic_search//biorxiv_chunked_memmap_metadata.json"
  data_folder: "/mnt/h/pubmed_semantic_search/pubmed_semantic_search//biorxiv_df/"
  chunk_size_bytes: 1073741824

medrxiv_config:
  embeddings_directory: "/mnt/h/pubmed_semantic_search/pubmed_semantic_search//medarxiv_embed/"
  npy_files_pattern: "*.npy"
  combined_data_file: "/mnt/h/pubmed_semantic_search/pubmed_semantic_search//medarxiv_df/database_2024-08-02.parquet"
  chunk_dir: "/home/dzyla/chunked/chunked_medarxiv_embeddings/"
  metadata_path: "/mnt/h/pubmed_semantic_search/pubmed_semantic_search//medarxiv_chunked_memmap_metadata.json"
  data_folder: "/mnt/h/pubmed_semantic_search/pubmed_semantic_search//medarxiv_df/"
  chunk_size_bytes: 1073741824

arxiv_config:
  embeddings_directory: "/mnt/h/pubmed_semantic_search/pubmed_semantic_search//arxiv_embed/"
  npy_files_pattern: "*.npy"
  chunk_dir: "/home/dzyla/chunked/chunked_arxiv_embeddings/"
  metadata_path: "/mnt/h/pubmed_semantic_search/pubmed_semantic_search//arxiv_chunked_memmap_metadata.json" 
  data_folder: "/mnt/h/pubmed_semantic_search/pubmed_semantic_search//arxiv_df/"
  chunk_size_bytes: 1073741824
